application:
  kakao-api:
    admin-key: 2e5db1d18c9deb08b6a8011850b40446
    domain-id: 139
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat

logging:
  level:
    sql: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    vault:
      enabled: true
      host: vault.dev.klaytn.com
      port: 443
      scheme: https
      authentication: APPROLE
      app-role:
        role-id: ed3d9ac7-9a9b-d1a8-7da9-fb120ad3989c
        secret-id: 4fcdea86-ed8f-f618-4777-eeb3521e451e
  config:
    import: vault://klip/klip-membership
  datasource:
    url: jdbc:h2:mem:local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE; # Vault
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 69090294389-2pnugpnhjdm5odpk89kdjc318860pb9b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


