# noinspection SpringBootApplicationYaml
application:
  version: ${_applicationVersion}  # from build.gradle.kts

spring:
  data:
    redis:
      repositories:
        enabled: false
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  messages:
    basename: classpath:message/errors
    fallback-to-system-locale: false
    use-code-as-default-message: true
  profiles:
    active: local         # default profile

springdoc:
  api-docs:
    enabled: false
  packages-to-scan:
    - com.klipwallet.membership.controller
    - com.klipwallet.membership.config
    - com.klipwallet.membership.dto
    - com.klipwallet.membership.entity
  show-actuator: true
  swagger-ui:
    enabled: false
    path: /swagger-ui