# local: 인프라 의존을 최소화하는 local 개발 환경. w/o vault(without-local-dev.properties)
application:
  kakao-api:
    #   admin-key:   from local.properties
    #   domain-id:   from local.properties
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: ${bgms_pw}  # from local.properties
  klip-drops-internal:
    api-url: http://localhost:3100 # kubectl port-forward svc/klip-drops 3100:3100

cloud:
  aws:
    s3:
      bucket: klip-membership-fe-dev
      prefix: dist
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      distribution-domain: membership.dev.klipwallet.com

logging:
  level:
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      client:
        config:
          default:
            logger-level: full
    vault:
      enabled: false
  config:
    import:
      - optional:classpath:/local.properties   # Generate it yourself
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            #client-id:       from local.properties
            #client-secret:   from local.properties
            scope: profile, email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


