application:
  kakao-api:
    #   admin-key:   from Value /klip/klip-membership
    #   domain-id:   from Value /klip/klip-membership
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: \${bgms_pw}  # from Vault /klip/common

logging:
  level:
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

cloud:
  aws:
    s3:
      bucket: klip-membership-fe-dev
      prefix: dist
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      distribution-domain: membership.dev.klipwallet.com

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
    vault:
      enabled: true
      host: vault.dev.klaytn.com
      port: 443
      token: ${G_VAULT_TOKEN}   # from build.gradle.kts
  config:
    import: vault://klip/klip-membership, vault://klip/common
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 69090294389-2pnugpnhjdm5odpk89kdjc318860pb9b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: \${spring.security.oauth2.client.registration.google.provider}
      client-id: \${spring.security.oauth2.client.registration.google.client-id}
      client-secret: \${spring.security.oauth2.client.registration.google.client-secret}
      realm: \${spring.security.oauth2.client.registration.google.provider}


