# noinspection SpringBootApplicationYaml
application:
  version: ${G_APPLICATION_VERSION}  # from build.gradle.kts
  bgms:
    invite-operator-template-code: receive_welcome_card_02
  developer:
    super-admin: gene.goh@groundx.xyz
    emails:
      - jordan.jung@groundx.xyz
      - ian.han@groundx.xyz
      - winnie.byun@groundx.xyz
      - rachel.lee@groundx.xyz
      - ted.jeong@groundx.xyz
      - twinsen.kim@groundx.xyz
      - sello.lee@groundx.xyz

logging:
  group:
    openfeign:
      - com.klipwallet.membership.adaptor.kakao.biztalk.BgmsApiClient
      - com.klipwallet.membership.adaptor.kakao.KakaoApiClient

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
      show-details: always
  health:
    redis:
      enabled: true   # Redis Session 때문에 활성화 시킴. Fallback to Jdbc Session 고민 중
    refresh:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        name: KMSESSION

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
      client:
        config:
          default:
            logger-level: basic
            connect-timeout: 2000
            read-timeout: 8000
          bgms:
            url: \${application.bgms.api-url}
          kakao:
            url: \${application.kakao-api.openlink-url}
          kas:
            url: \${application.kas-api.th-url}
          klip-drops-internal:
            url: \${application.klip-drops-internal.api-url}
      compression:
        request:
          enabled: true
        response:
          enabled: true
    vault:
      enabled: false
  data:
    redis:
      repositories:
        enabled: false
    web:
      pageable:
        page-parameter: page
        one-indexed-parameters: true
        max-page-size: 1000
        default-page-size: 20
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.discriminator.ignore_explicit_for_joined: false
  messages:
    basename: classpath:message/errors
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          google:
            provider: google
            #client-id:       from local.properties
            #client-secret:   from local.properties
            scope: profile, email
          kakao:
            provider: kakao
            client-id: \${kakao_rest_api_key} # from Vault /klip/common
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseScheme}://{baseHost}{basePort}/login/oauth2/code/{registrationId}'
            client-name: Kakao
            scope:
              - profile
              - account_email
              - talk_openchats
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
      file-size-threshold: 500KB
  profiles:
    default: local

springdoc:
  api-docs:
    enabled: false
  packages-to-scan:
    - com.klipwallet.membership.controller
    - com.klipwallet.membership.config
    - com.klipwallet.membership.dto
    - com.klipwallet.membership.entity
  show-actuator: true
  swagger-ui:
    enabled: false
    path: /swagger-ui
