application:
  kakao-api:
    admin-key: 2e5db1d18c9deb08b6a8011850b40446
    domain-id: 139
    user-id-type: user_id
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
    test-user-id: 2538023320 # Ian
    test-participant-id: 2439320002 # Winnie

logging:
  level:
    sql: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  health:
    redis:
      enabled: false
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    vault:
      enabled: false
  datasource:
    url: jdbc:h2:mem:local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 69090294389-2pnugpnhjdm5odpk89kdjc318860pb9b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



