application:
  klip-membership:
    env: dev
    tool-front-url: https://membership.dev.klipwallet.com
    admin-front-url: https://membership-admin.dev.klipwallet.com
  kakao-api:
    admin-key: ${kakao_admin_key}  # from Vault /klip/common
    #domain-id:   from Vault /klip/klip-membership
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  kas-api:
    th-url: https://th-api.qa-2.klaytn.com
    authorization: ${kas_authorization_key} # from local.properties
    chainId: ${kas_chain_id} # from local.properties
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: ${bgms_pw}  # from Vault /klip/common
    sender-key: ${bgms_sender_key}  # from Vault /klip/common
  klip-drops-internal:
    api-url: http://klip-drops.klip-drops-dev.svc.cluster.local:3100
  email:
    sender-email: developer@groundx.xyz # AWS SES에서 email verfiy된 주소 입력
  nft:
    klip-drops-sca: 0xb329ddcc6722c158c81BeDe6820dd419e6896486

cloud:
  aws:
    s3:
      bucket: klip-cms-dev
      prefix: dist
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      distribution-domain: klip-media.dev.klaytn.com

logging:
  level:
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
    vault:
      enabled: true
      host: vault.dev.klaytn.com
      port: 443
      namespace: vault
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
        role: klip-membership-role
        app-role-path: approle
  config:
    import: vault://klip/klip-membership, vault://klip/common
  data:
    redis:
      host: klip-membership-dev.s9wmjn.ng.0001.apn2.cache.amazonaws.com
      lettuce:
        pool:
          enabled: true
          max-idle: 16
          min-idle: 0
          max-active: 16
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create

  session:
    redis:
      repository-type: default
      namespace: ${application.klip-membership.env}    # 환경 별 prefix 설정. Key 예시: 'dev:sessions:{sessionId}'
    timeout: 30m

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


