#file: noinspection HttpUrlsUsage
# local: 인프라 의존을 최소화하는 local 개발 환경. w/o vault(without-local-dev.properties)
application:
  klip-membership:
    env: local
    tool-front-url: http://membership.local.klipwallet.com:3000
    admin-front-url: http://membership-admin.local.klipwallet.com:3000
  kakao-api:
    admin-key: ${kakao_admin_key} # from local.properties
    #   domain-id:   from local.properties
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  kas-api:
    th-url: https://th-api.qa-2.klaytn.com
    #    authorization: # from local.properties
    chainId: 8217
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: ${bgms_pw}  # from local.properties
    sender-key: ${bgms_sender_key}  # from local.properties
  klip-drops-internal:
    api-url: http://localhost:3100 # kubectl port-forward svc/klip-drops 3100:3100
  email:
    sender-email: developer@groundx.xyz # AWS SES에서 email verfiy된 주소 입력
  nft:
    klip-drops-sca: 0xb329ddcc6722c158c81BeDe6820dd419e6896486

cloud:
  aws:
    s3:
      bucket: klip-cms-dev
      prefix: dist
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      distribution-domain: klip-media.dev.klaytn.com

logging:
  level:
    root: info
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug
    org.springframework.security: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration   # redis session disabled
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
      client:
        config:
          default:
            logger-level: full
    vault:
      enabled: false
  config:
    import:
      - optional:classpath:/local.properties   # Generate it yourself
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


