logging:
  level:
    sql: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  health:
    redis:
      enabled: false
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    vault:
      enabled: false
  datasource:
    url: jdbc:h2:mem:local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 69090294389-2pnugpnhjdm5odpk89kdjc318860pb9b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



