application:
  kakao-api:
    #admin-key:   from Vault /klip/klip-membership
    #domain-id:   from Vault /klip/klip-membership
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: ${bgms_pw}  # from Vault /klip/common
  klip-drops-internal:
    api-url: http://localhost:3100 # kubectl port-forward svc/klip-drops 3100:3100

logging:
  level:
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
    vault:
      enabled: true
      host: vault.dev.klaytn.com
      port: 443
      namespace: vault
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
        role: klip-membership-role
        app-role-path: approle
  config:
    import: vault://klip/klip-membership, vault://klip/common
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            #client-id:       from Vault /klip/klip-membership
            #client-secret:   from Vault /klip/klip-membership
            scope: profile, email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


