# noinspection SpringBootApplicationYaml
application:
  version: ${_applicationVersion}  # from build.gradle.kts

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
  health:
    redis:
      enabled: false
    refresh:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    vault:
      enabled: false
  data:
    redis:
      repositories:
        enabled: false
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  messages:
    basename: classpath:message/errors
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
      file-size-threshold: 500KB
  profiles:
    active: local         # default profile

springdoc:
  api-docs:
    enabled: false
  packages-to-scan:
    - com.klipwallet.membership.controller
    - com.klipwallet.membership.config
    - com.klipwallet.membership.dto
    - com.klipwallet.membership.entity
  show-actuator: true
  swagger-ui:
    enabled: false
    path: /swagger-ui
