logging:
  level:
    sql: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  health:
    redis:
      enabled: false
  newrelic:
    metrics:
      export:
        enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    vault:
      enabled: false
  datasource:
    url: jdbc:h2:mem:local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
#  security:
#    oauth2:
#      client:
#        tool-by-google: # membership-tool 구글 oauth2 인증
#          client-id: 1
#          client-secret: 1111111111
#          scope: profile, email
#        admin-by-google: # membership-admin 구글 oauth2 인증
#          client-id: 2
#          client-secret: 2222222222
#          scope: profile, email


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



