application:
  kakao-api:
    #admin-key:   from Vault /klip/klip-membership
    #domain-id:   from Vault /klip/klip-membership
    openlink-url: http://kapi.kakao.com/v1/internal/talk/openchat
  bgms:
    api-url: https://www.biztalk-api.com
    id: groundx_prod_dev
    password: ${bgms_pw}  # from Vault /klip/common
  klip-drops-internal:
    api-url: http://klip-drops.klip-drops-dev.svc.cluster.local:3100

cloud:
  aws:
    s3:
      bucket: klip-membership-fe-dev
      prefix: dist
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront:
      distribution-domain: membership.dev.klipwallet.com

logging:
  level:
    sql: debug
    openfeign: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  newrelic:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
    vault:
      enabled: true
      host: vault.dev.klaytn.com
      port: 443
      namespace: vault
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
        role: klip-membership-role
        app-role-path: approle
  config:
    import: vault://klip/klip-membership, vault://klip/common
  data:
    redis:
      host: klip-membership-dev.s9wmjn.ng.0001.apn2.cache.amazonaws.com
      lettuce:
        pool:
          enabled: true
          max-idle: 16
          min-idle: 0
          max-active: 16
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            #client-id:       from Vault /klip/klip-membership
            #client-secret:   from Vault /klip/klip-membership
            scope: profile, email
  session:
    redis:
      repository-type: default
      namespace: dev    # 환경 별 predfix 설정. Key 예시: 'dev:sessions:{sessionId}'
    timeout: 1h         # Session 만료 1시간

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      app-name: ${spring.security.oauth2.client.registration.google.provider}
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      realm: ${spring.security.oauth2.client.registration.google.provider}


