# noinspection SpringBootApplicationYaml
application:
  version: ${G_APPLICATION_VERSION}  # from build.gradle.kts

logging:
  group:
    openfeign:
      - com.klipwallet.membership.adaptor.biztalk.BgmsApiClient
      - com.klipwallet.membership.adaptor.kakao.KakaoApiClient

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
  health:
    redis:
      enabled: false
    refresh:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
      client:
        config:
          default:
            logger-level: basic
            connect-timeout: 2000
            read-timeout: 8000
          bgms:
            url: \${application.bgms.api-url}
          kakao:
            url: \${application.kakao-api.openlink-url}
          klip-drops-internal:
            url: \${application.klip-drops-internal.api-url}
      compression:
        request:
          enabled: true
        response:
          enabled: true
    vault:
      enabled: false
  data:
    redis:
      repositories:
        enabled: false
    web:
      pageable:
        page-parameter: page
        one-indexed-parameters: true
        max-page-size: 1000
        default-page-size: 20

  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  messages:
    basename: classpath:message/errors
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
      file-size-threshold: 500KB
  profiles:
    default: local

springdoc:
  api-docs:
    enabled: false
  packages-to-scan:
    - com.klipwallet.membership.controller
    - com.klipwallet.membership.config
    - com.klipwallet.membership.dto
    - com.klipwallet.membership.entity
  show-actuator: true
  swagger-ui:
    enabled: false
    path: /swagger-ui
