logging:
  level:
    sql: debug
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: debug

management:
  health:
    redis:
      enabled: false
  newrelic:
    metrics:
      export:
        enabled: false

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    vault:
      enabled: false
  datasource:
    url: jdbc:h2:mem:local;MODE=MYSQL;
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true



